<a href="https://colab.research.google.com/github/querenneves/NLTK/blob/main/Corpus_e_Similaridade_Textual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
poema = """E agora, José?
A festa acabou,
a luz apagou,
o povo sumiu,
a noite esfriou,
e agora, José?
e agora, você?
você que é sem nome,
que zomba dos outros,
você que faz versos,
que ama, protesta?
e agora, José?

Está sem mulher,
está sem discurso,
está sem carinho,
já não pode beber,
já não pode fumar,
cuspir já não pode,
a noite esfriou,
o dia não veio,
o bonde não veio,
o riso não veio,
não veio a utopia
e tudo acabou
e tudo fugiu
e tudo mofou,
e agora, José?

E agora, José?
Sua doce palavra,
seu instante de febre,
sua gula e jejum,
sua biblioteca,
sua lavra de ouro,
seu terno de vidro,
sua incoerência,
seu ódio - e agora?

Com a chave na mão
quer abrir a porta,
não existe porta;
quer morrer no mar,
mas o mar secou;
quer ir para Minas,
Minas não há mais.
José, e agora?

Se você gritasse,
se você gemesse,
se você tocasse
a valsa vienense,
se você dormisse,
se você cansasse,
se você morresse...
Mas você não morre,
você é duro, José!

Sozinho no escuro
qual bicho-do-mato,
sem teogonia,
sem parede nua
para se encostar,
sem cavalo preto
que fuja a galope,
você marcha, José!
José, para onde?"""

In [12]:
import nltk
from nltk import tokenize
nltk.download('punkt') # necessário para baixar o tokenizador
nltk.download('punkt_tab', quiet=True) # necessário para baixar o tokenizador para português

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

Contagem de **Tokens**

In [13]:
tokens = tokenize.word_tokenize(poema, language="portuguese")
minusculas = tokenize.word_tokenize(poema.lower(), language="portuguese")

vocabulario = set(minusculas)

print("Quantidade de tokens: ",len(tokens))
print("Quantidade de types: ",len(vocabulario))

Quantidade de tokens:  274
Quantidade de types:  109


In [14]:
print(tokens)
print(len(tokens))

['E', 'agora', ',', 'José', '?', 'A', 'festa', 'acabou', ',', 'a', 'luz', 'apagou', ',', 'o', 'povo', 'sumiu', ',', 'a', 'noite', 'esfriou', ',', 'e', 'agora', ',', 'José', '?', 'e', 'agora', ',', 'você', '?', 'você', 'que', 'é', 'sem', 'nome', ',', 'que', 'zomba', 'dos', 'outros', ',', 'você', 'que', 'faz', 'versos', ',', 'que', 'ama', ',', 'protesta', '?', 'e', 'agora', ',', 'José', '?', 'Está', 'sem', 'mulher', ',', 'está', 'sem', 'discurso', ',', 'está', 'sem', 'carinho', ',', 'já', 'não', 'pode', 'beber', ',', 'já', 'não', 'pode', 'fumar', ',', 'cuspir', 'já', 'não', 'pode', ',', 'a', 'noite', 'esfriou', ',', 'o', 'dia', 'não', 'veio', ',', 'o', 'bonde', 'não', 'veio', ',', 'o', 'riso', 'não', 'veio', ',', 'não', 'veio', 'a', 'utopia', 'e', 'tudo', 'acabou', 'e', 'tudo', 'fugiu', 'e', 'tudo', 'mofou', ',', 'e', 'agora', ',', 'José', '?', 'E', 'agora', ',', 'José', '?', 'Sua', 'doce', 'palavra', ',', 'seu', 'instante', 'de', 'febre', ',', 'sua', 'gula', 'e', 'jejum', ',', 'sua', 'b

In [15]:
print(vocabulario)
print(len(vocabulario))

{'valsa', 'noite', '...', 'riso', 'utopia', 'palavra', 'discurso', 'gula', 'a', 'marcha', 'nua', 'instante', 'mas', 'morresse', 'morrer', 'gemesse', 'de', 'incoerência', 'festa', 'duro', 'e', ';', 'já', 'ouro', 'sem', 'acabou', 'porta', 'não', 'versos', 'mulher', 'apagou', 'terno', 'onde', 'encostar', 'há', 'você', 'sozinho', '.', '!', 'ódio', 'que', 'outros', 'mofou', 'para', '?', 'está', 'pode', 'gritasse', 'quer', 'ir', 'josé', 'fugiu', '-', 'se', 'teogonia', 'galope', 'jejum', 'luz', 'febre', 'doce', 'parede', 'mão', 'existe', 'nome', 'bonde', 'cavalo', 'biblioteca', ',', 'é', 'minas', 'agora', 'veio', 'fuja', 'dia', 'dos', 'carinho', 'chave', 'mar', 'abrir', 'seu', 'tudo', 'faz', 'preto', 'morre', 'no', 'o', 'cansasse', 'povo', 'sumiu', 'beber', 'lavra', 'escuro', 'zomba', 'com', 'mais', 'tocasse', 'qual', 'protesta', 'bicho-do-mato', 'esfriou', 'vidro', 'na', 'secou', 'fumar', 'cuspir', 'dormisse', 'ama', 'vienense', 'sua'}
109


Segmentação de sentenças

In [16]:
sentencas = nltk.sent_tokenize(poema, language="portuguese")
print(sentencas)
print(len(sentencas))

['E agora, José?', 'A festa acabou,\na luz apagou,\no povo sumiu,\na noite esfriou,\ne agora, José?', 'e agora, você?', 'você que é sem nome,\nque zomba dos outros,\nvocê que faz versos,\nque ama, protesta?', 'e agora, José?', 'Está sem mulher,\nestá sem discurso,\nestá sem carinho,\njá não pode beber,\njá não pode fumar,\ncuspir já não pode,\na noite esfriou,\no dia não veio,\no bonde não veio,\no riso não veio,\nnão veio a utopia\ne tudo acabou\ne tudo fugiu\ne tudo mofou,\ne agora, José?', 'E agora, José?', 'Sua doce palavra,\nseu instante de febre,\nsua gula e jejum,\nsua biblioteca,\nsua lavra de ouro,\nseu terno de vidro,\nsua incoerência,\nseu ódio - e agora?', 'Com a chave na mão\nquer abrir a porta,\nnão existe porta;\nquer morrer no mar,\nmas o mar secou;\nquer ir para Minas,\nMinas não há mais.', 'José, e agora?', 'Se você gritasse,\nse você gemesse,\nse você tocasse\na valsa vienense,\nse você dormisse,\nse você cansasse,\nse você morresse...', 'Mas você não morre,\nvocê é 

# Similaridade textual

In [18]:
import pandas as pd
import numpy as np

In [19]:
texts = ['Goku is a hero in the Dragon Ball since 1989! Goku saved the earth so many times.',
         'The 7 Dragon balls can make wishes come true! Each ball contains his own dragon.',
         'If the wishes are superfluous, the dragon balls will become dark.' ,
         'Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.',
         "A knight of the zodiac wear a bronze, silver or a gold cloth to protect Athena.",
         'Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.']
classes = ['Dragon Ball', 'Dragon Ball', 'Dragon Ball', 'Cav. Zod.', 'Cav. Zod.', 'Cav. Zod.']

df = pd.DataFrame({'texts': texts, 'classes': classes})
print(df)

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.


## Similaridade Textual baseada em caracteres - A distância de Levenshtein


In [20]:
def levenshtein(seq1, seq2):
    # criar uma matriz
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))

    # setar número de colunas (0, n-1)
    for x in range(size_x):
        matrix [x, 0] = x

    # setar número de linhas (0, n-1)
    for y in range(size_y):
        matrix [0, y] = y

    # calcular a distancia
    for x in range(1, size_x):
        for y in range(1, size_y):
            # se os caracteres sao iguais, nao aumenta a distancia
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = matrix[x-1, y-1]
            # se são diferentes, aumenta a distancia em 1
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )

    # imprime a matriz de calculo da distancia
    # list(seq1) converte string em uma lista de caracteres
    print(pd.DataFrame(matrix[1:,1:], index=list(seq1), columns=list(seq2)))

    return (matrix[size_x - 1, size_y - 1])

In [21]:
levenshtein('medicina','medico')

     m    e    d    i    c    o
m  0.0  1.0  2.0  3.0  4.0  5.0
e  1.0  0.0  1.0  2.0  3.0  4.0
d  2.0  1.0  0.0  1.0  2.0  3.0
i  3.0  2.0  1.0  0.0  1.0  2.0
c  4.0  3.0  2.0  1.0  0.0  1.0
i  5.0  4.0  3.0  2.0  1.0  1.0
n  6.0  5.0  4.0  3.0  2.0  2.0
a  7.0  6.0  5.0  4.0  3.0  3.0


np.float64(3.0)

In [22]:
print(df)
print ("------")
doc_id_a = 3 # id do texto 1
doc_id_b = 2 # id do texto 2
print("texto 1: ",df.loc[doc_id_a]['texts'])
print("texto 2: ",df.loc[doc_id_b]['texts'])
print ("------")

levenshtein(df.loc[doc_id_a]['texts'],df.loc[doc_id_b]['texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.
------
texto 1:  Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.
texto 2:  If the wishes are superfluous, the dragon balls will become dark.
------
        I      f           t     h     e           w     i     s  ...     c  \
S     1.0    2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  ...  56.0   
e     2.0    2.0   3.0   4.0   5.0   5.0   6.0   7.0   8.0   9.0  ...  55.0   
i     3.0    3.0   3.0   4.0   5.0   6.0   6.0   7.0   7.0   8.0  ...  54.0   
y     4.0    4.0   4

np.float64(76.0)

## Similaridade Textual baseada em Termos - Vetorizando os documentos de treinamento

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
"""Criando o objeto vetorizador (convertendo para letras minúsculas, removendo as stopwords especificadas em uma lista
   e apenas mantendo os termos que ocorreram em dois ou mais documentos"""
vetorizador = CountVectorizer(lowercase=True,
                              stop_words=['is', 'are', 'a', 'or', 'to', 'in', 'the', 'so', 'since', 'many', 'of'],
                              min_df=2,
                              dtype=np.int16
                              )

In [24]:
# Obtendo o vocabulário
vetorizador.fit(df['texts'])

CountVectorizer(dtype=<class 'numpy.int16'>, min_df=2,
                stop_words=['is', 'are', 'a', 'or', 'to', 'in', 'the', 'so',
                            'since', 'many', 'of'])

In [25]:
# Gerando a representação estruturada a partir do vocabulário ajustado
representacao = vetorizador.transform(df['texts'])
# A representação retornada é uma matriz em um formato esparso  (posso gerar o array usando toArray())
representacao
rep_array = representacao.toarray() # a partir daqui podemos aplicar as funções de similaridade
print(rep_array)

[[0 1 0 0 1 0 0 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 0 0 0 1 0]
 [1 0 0 1 0 1 1 1 1 1 0 1]
 [1 0 0 1 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 1 0 0 1]]


### Cosseno

In [26]:
from sklearn.metrics.pairwise import cosine_similarity
matrix_sim = cosine_similarity(rep_array)

In [27]:
matrix_sim

array([[1.        , 0.56694671, 0.28867513, 0.35355339, 0.        ,
        0.        ],
       [0.56694671, 1.        , 0.87287156, 0.        , 0.        ,
        0.        ],
       [0.28867513, 0.87287156, 1.        , 0.        , 0.        ,
        0.        ],
       [0.35355339, 0.        , 0.        , 1.        , 0.70710678,
        0.61237244],
       [0.        , 0.        , 0.        , 0.70710678, 1.        ,
        0.28867513],
       [0.        , 0.        , 0.        , 0.61237244, 0.28867513,
        1.        ]])

In [28]:
def most_similar(id_doc, matrix):
  matrix_sim = cosine_similarity(matrix)
  best_sim = -1
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim > best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [29]:
print(df)
print ("------")
doc_id = 5
print("Texto: ", df.loc[doc_id]['texts'])
print("Texto mais parecido: ", df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.
------
Texto:  Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.
Texto mais parecido:  Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.


### Jaccard

"O índice de Jaccard é uma estatística para comparar e medir a semelhança entre dois conjuntos diferentes. É uma proporção da interseção de dois conjuntos sobre a união deles.

Se você tiver um número finito representativo de elementos para uma observação específica e quiser comparar essa observação com outra observação, poderá contar o número de itens comuns a esses dois conjuntos. É um ajuste natural para comparar postagens se você conhece as *tags* representativas das postagens para medir o quão semelhantes dois artigos são em termos de *tags*."

In [30]:
from sklearn.metrics import pairwise_distances

In [31]:
def most_similar(id_doc, matrix):
  matrix_sim = 1 - pairwise_distances(matrix, metric='jaccard') # como é medida de distância (valor entre 0 e 1), utilizar o complemento
  best_sim = -1
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim > best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [32]:
matrix_sim = 1 - pairwise_distances(rep_array, metric='jaccard')
matrix_sim

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/pairwise.py:2466: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


array([[1.        , 0.33333333, 0.16666667, 0.2       , 0.        ,
        0.        ],
       [0.33333333, 1.        , 0.75      , 0.        , 0.        ,
        0.        ],
       [0.16666667, 0.75      , 1.        , 0.        , 0.        ,
        0.        ],
       [0.2       , 0.        , 0.        , 1.        , 0.5       ,
        0.375     ],
       [0.        , 0.        , 0.        , 0.5       , 1.        ,
        0.16666667],
       [0.        , 0.        , 0.        , 0.375     , 0.16666667,
        1.        ]])

In [33]:
import warnings
warnings.filterwarnings("ignore") # não imprimir o warning por não utilizar valores binários

print(df)
print ("------")
doc_id = 5
print("Texto: ", df.loc[doc_id]['texts'])
print("Texto mais parecido: ", df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.
------
Texto:  Saint Seiya: Knights of the Zodiac is a Japanese manga in which mystical warriors called the Saints fight wearing sacred cloths.
Texto mais parecido:  Seiya is a bronze knight and is one of the main Knights of the Zodiac. He saved Athena several times.


### Jaccard backup (testar depois com os mesmos textos das outras)

In [34]:
def jaccard_similarity(x,y):
  """ retorna a similaridade de jaccard entre duas listas """
  intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
  union_cardinality = len(set.union(*[set(x), set(y)]))
  return intersection_cardinality/float(union_cardinality)

texto1 = rep_array[5]
texto2 = rep_array[3]

print(texto1)
print(texto2)

print(jaccard_similarity(texto1, texto2))

print(matrix_sim[5][3])

[0 0 0 0 0 0 1 0 1 0 0 1]
[1 0 0 1 0 1 1 1 1 1 0 1]
1.0
0.375


### Euclidiana

In [35]:
def most_similar(id_doc, matrix):
  matrix_sim = pairwise_distances(matrix, metric='euclidean')
  best_sim = 99999999
  id_best_sim = -1;
  for id, doc_sim in enumerate(matrix_sim[id_doc]):
    if id != id_doc:
      if doc_sim <= best_sim:
        best_sim = doc_sim
        id_best_sim = id
  return id_best_sim

In [36]:
matrix_sim = pairwise_distances(rep_array, metric='euclidean')
matrix_sim

array([[0.        , 2.23606798, 2.23606798, 2.82842712, 2.82842712,
        2.64575131],
       [2.23606798, 0.        , 1.41421356, 3.87298335, 3.31662479,
        3.16227766],
       [2.23606798, 1.41421356, 0.        , 3.31662479, 2.64575131,
        2.44948974],
       [2.82842712, 3.87298335, 3.31662479, 0.        , 2.        ,
        2.23606798],
       [2.82842712, 3.31662479, 2.64575131, 2.        , 0.        ,
        2.23606798],
       [2.64575131, 3.16227766, 2.44948974, 2.23606798, 2.23606798,
        0.        ]])

In [37]:
print(df)
print ("------")
doc_id = 5
#df.loc[doc_id]['texts']
df.loc[most_similar(doc_id, rep_array)]['texts']

                                               texts      classes
0  Goku is a hero in the Dragon Ball since 1989! ...  Dragon Ball
1  The 7 Dragon balls can make wishes come true! ...  Dragon Ball
2  If the wishes are superfluous, the dragon ball...  Dragon Ball
3  Seiya is a bronze knight and is one of the mai...    Cav. Zod.
4  A knight of the zodiac wear a bronze, silver o...    Cav. Zod.
5  Saint Seiya: Knights of the Zodiac is a Japane...    Cav. Zod.
------


'A knight of the zodiac wear a bronze, silver or a gold cloth to protect Athena.'